apiVersion: v1
kind: Namespace
metadata:
  name: openshift-compliance
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: compliance-operator
  namespace: openshift-compliance
spec:
  targetNamespaces:
    - openshift-compliance
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: compliance-operator
  namespace: openshift-compliance
spec:
  channel: '{{ fromConfigMap "default" "opp-policy-config" "compliance_operator_channel" }}'
  installPlanApproval: Automatic
  name: compliance-operator
  source: '{{ fromConfigMap "default" "opp-policy-config" "compliance_operator_source" }}'
  sourceNamespace: '{{ fromConfigMap "default" "opp-policy-config" "compliance_operator_sourcenamespace" }}'
---
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  namespace: openshift-compliance
spec:
  displayName: Compliance Operator
status:
  phase: Succeeded   # check the csv status to determine if operator is running or not
